### ISSUE TITLE
Easy Container Errors

### ISSUE THREAD

**Issue by Karma-Fox** [Kenan2000/CDDA-Structured-Kenan-Modpack#304]
Python script needs a quick update;

Here is the error;
```
E:\Downloads\dda\game0>generate_containers.py "data\json\items"
Traceback (most recent call last):
  File "E:\Downloads\dda\game0\generate_containers.py", line 196, in <module>
    files = get_files(input_path)
  File "E:\Downloads\dda\game0\generate_containers.py", line 105, in get_files
    changed_containers = parse_file(file)
  File "E:\Downloads\dda\game0\generate_containers.py", line 68, in parse_file
    json_file = json.load(f)
  File "C:\Users\numa\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\numa\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 9821: character maps to <undefined>
```

Here is the fix I've found to work

```
Replace Line 67====     with open(file, 'r') as f:
With================    with open(file, encoding="utf8") as f:
```

**Comment by Kenan2000** [comment]
Very good work of finding how to fix these errors

**Comment by Kenan2000** [comment]
Hopefully fixed in this update as well
